spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/task_manager"
    password: "@Blessing22#"
    username: "root"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  error:
    whitelabel:
      enabled: false

